version: "3.9"
services:
    web:
      build: .
      environment:
        - ASPNETCORE_ENVIRONMENT=DockerDevelopment
      ports:
        - "8000:80"
      depends_on:
        - db
    db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
        SA_PASSWORD: "<SAPassWORD>"
        ACCEPT_EULA: "Y"